apiVersion: v1
kind: ReplicationController
metadata:
  name: node-test-rc
spec:
  replicas: 3
  selector:
    app: node-test
  template:
    metadata:
      name: node-test
      labels:
        app: node-test
    spec:
      containers:
      - name: node-test
        image: node-test
        ports:
        - containerPort: 80
