apiVersion: v1
kind: Pod
metadata:
  name: mos-webserver
  labels:
    app: mos-webserver
spec:
  containers:
  - name: mos-webserver
    image: mos-webserver
    imagePullPolicy: Never
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: "DUMMY_VALUE"
        value: "This is dummy value from K8s"
      - name: "DUMMY_VALUE_2"
        value: "This is dummy value from K8s"
