apiVersion: v1
kind: Pod
metadata:
  name: cpp-executor
  labels:
    name: cpp-executor
spec:
  restartPolicy: Never
  volumes:
    - name: shared
      hostPath:
        path: "/Users/ShipNK/workspace/k8s/k8s-sandbox/executors/shared"
        type: Directory
  containers:
  - name: cpp-executor
    image: cpp-executor
    imagePullPolicy: Never
    env:
      - name: "SOURCE_FILE"
        value: "/shared/test.cpp"
      - name: "INPUT_FILE"
        value: "/shared/input.txt"
    volumeMounts:
      - mountPath: "/shared"
        name: shared
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
