apiVersion: v1
kind: Service
metadata:
  name: kubia-svc
spec:
  selector:
    app: kubia
  type: LoadBalancer
  ports:
    - name: kubia
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30036
  externalIPs: 
    - 192.168.0.150
